### ISSUE TITLE
ClientException: 'page' not found on model

### ISSUE THREAD

**Issue by tmattsson** [intercom/intercom-java#111]
## Version info
- intercom-java version: 2.0.0
- Java version: 1.7
## Expected behavior

Receive users in segment.
## Actual behavior

Fails with exception, possibly a marshalling problem.
## Steps to reproduce
1.  Query for users in segment
## Logs

io.intercom.api.ClientException: 'page' not found on model
    at io.intercom.api.HttpClient.throwException(HttpClient.java:205)
    at io.intercom.api.HttpClient.handleError(HttpClient.java:164)
    at io.intercom.api.HttpClient.runRequest(HttpClient.java:150)
    at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:105)
    at io.intercom.api.HttpClient.get(HttpClient.java:81)
    at io.intercom.api.HttpClient.get(HttpClient.java:77)
    at io.intercom.api.TypedDataCollection.fetchNextPage(TypedDataCollection.java:44)
    at io.intercom.api.UserCollection.nextPage(UserCollection.java:33)
    at io.intercom.api.UserCollection.nextPage(UserCollection.java:9)
    at io.intercom.api.TypedDataCollectionIterator.hasNext(TypedDataCollectionIterator.java:19)
    at io.intercom.api.UserCollection.hasNext(UserCollection.java:37)

**Comment by bobjflong** [comment]
Hi @tmattsson 

I believe this is caused when paging extremely deeply. We've released a more efficient Scroll API for this purpose: https://developers.intercom.io/reference#iterating-over-all-users. It's not in `intercom-java` yet, but it would be good to try out.

**Comment by tmattsson** [comment]
Thanks for your reply, does the new API support querying by segment or tag? If so, is this done with the same parameters as in the user listing API, segment_id and tag_id?

**Comment by tmattsson** [comment]
The scroll API works fine and I am able to retrieve all users. I then filter out those in the segment I'm working with and get the set of users that I need. This takes four times longer than the user listing API did. My largest segment contains 20% of my users so I'm retrieving 5 times more than I actually need.

**Comment by choran** [comment]
Hi @tmattsson 
We are just following up on some older issues here. I see with the scroll you were able to use to to list all users. Unfortunately, with the user listing you are not able to list more than 10,00 users. The trade off with scroll is that it can perform listing for larger numbers of users but it does not allow for filtering or listing be segment as the user API does. We are looking into this area or listing large amounts of resource to see if we can improve the filtering and sorting. However, for the moment the scroll is the best way to do this.
I will close this issue for now unless you think there is anything else you would like clarified or a reason you would like to keep this issue open. If so please feel free to re-open
Thanks
Cathal
