### ISSUE TITLE
JsonMappingException on Subscription.list()

### ISSUE THREAD

**Issue by catacraciun** [intercom/intercom-java#123]
## Version info
- intercom-java version: 2.2.0
- Java version: 1.8
## Expected behavior

Subscription.list() should return the list of subscriptions.
## Actual behavior

It throws com.fasterxml.jackson.databind.JsonMappingException, because there are two possible cases of Subscription.metadata values:
1. 
`"metadata": {
        "event_names": [
          "nps-response"
        ]
      }`
In this case, it works well, because can be deserialized in Map `Map<String, ArrayList<String>>`
2.
`"metadata": {
        "channel": "all"
      }`
In this case, it throws the JsonMappingException, because this cannot be deserialized in `Map<String, ArrayList<String>>`.
## Steps to reproduce
1. Call Subscription.list()
2. Depending on the configured subscriptions, you will get this exception.
## Logs

```
Caused by: io.intercom.api.IntercomException: Local exception calling [https://api.intercom.io//subscriptions]. Check connectivity and settings. [Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@5340ca7c; line: 1, column: 2611] (through reference chain: io.intercom.api.SubscriptionCollection["items"]->java.util.ArrayList[4]->io.intercom.api.Subscription["metadata"]->java.util.LinkedHashMap["channel"])]
    at io.intercom.api.HttpClient.throwLocalException(HttpClient.java:117)
    at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:105)
    at io.intercom.api.HttpClient.get(HttpClient.java:79)
    at io.intercom.api.HttpClient.get(HttpClient.java:75)
    at io.intercom.api.DataResource.list(DataResource.java:58)
    at io.intercom.api.Subscription.list(Subscription.java:42)
    at com.konsus.server.service.intercom.IntercomConfig.findSubscription(IntercomConfig.java:148)
    at com.konsus.server.service.intercom.IntercomConfig.requireSubscription(IntercomConfig.java:137)
    at com.konsus.server.service.intercom.IntercomConfig.subscribeWebHooks(IntercomConfig.java:120)
    at com.konsus.server.service.intercom.IntercomConfig.onApplicationEvent(IntercomConfig.java:103)
    at com.konsus.server.service.intercom.IntercomConfig.onApplicationEvent(IntercomConfig.java:26)
    at com.konsus.server.service.intercom.IntercomConfig$$EnhancerBySpringCGLIB$$dfe151b7.onApplicationEvent(<generated>)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
    at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
    at org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:98)
    at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79)
    at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
    at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:149)
    at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:129)
    at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85)
    at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5240)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
    ... 42 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@5340ca7c; line: 1, column: 2611] (through reference chain: io.intercom.api.SubscriptionCollection["items"]->java.util.ArrayList[4]->io.intercom.api.Subscription["metadata"]->java.util.LinkedHashMap["channel"])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:853)
    at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:240)
    at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:171)
    at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:161)
    at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:19)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:495)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
    at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2810)
    at io.intercom.api.HttpClient.readEntity(HttpClient.java:185)
    at io.intercom.api.HttpClient.handleSuccess(HttpClient.java:169)
    at io.intercom.api.HttpClient.runRequest(HttpClient.java:146)
    at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:103)
    ... 66 more
```

This is an example of JSON response retrieved from intercom API, which fails:

``` javascript
{
  "type": "notification_subscription.list",
  "items": [
    {
      "type": "notification_subscription",
      "id": "<private>",
      "created_at": 1455493097,
      "updated_at": 1455578439,
      "url": "<private>",
      "topics": [
        "conversation.admin.replied",
        "conversation.admin.opened",
        "conversation.admin.closed",
        "conversation.admin.assigned"
      ],
      "active": true,
      "metadata": {
        "event_names": [
          "invited-friend"
        ]
      },
      "hub_secret": "",
      "links": {},
      "notes": [],
      "service_type": "web",
      "app_id": "<private>",
      "mode": "point"
    },
    {
      "type": "notification_subscription",
      "id": "<private>",
      "created_at": 1453575037,
      "updated_at": 1468970641,
      "url": "<private>",
      "topics": [
        "conversation.user.created",
        "conversation.user.replied",
        "conversation.admin.replied",
        "conversation.admin.single.created",
        "conversation.admin.assigned",
        "conversation.admin.noted",
        "conversation.admin.closed",
        "conversation.admin.opened"
      ],
      "active": true,
      "metadata": {},
      "hub_secret": "<private>",
      "links": {},
      "notes": [],
      "service_type": "web",
      "app_id": "<private>",
      "mode": "point"
    },
    {
      "type": "notification_subscription",
      "id": "<private>",
      "created_at": 1467027770,
      "updated_at": 1467028195,
      "url": "<private>",
      "topics": [
        "conversation.admin.noted"
      ],
      "active": true,
      "metadata": {
        "event_names": [
          null
        ]
      },
      "hub_secret": null,
      "links": {},
      "notes": [],
      "service_type": "web",
      "app_id": "<private>",
      "mode": "point"
    },
    {
      "type": "notification_subscription",
      "id": "<private>",
      "created_at": 1455760391,
      "updated_at": 1458687700,
      "url": "<private>",
      "topics": [
        "conversation.user.created"
      ],
      "active": true,
      "metadata": {
        "channel": "all"
      },
      "hub_secret": null,
      "links": {},
      "notes": [],
      "service_type": "slack",
      "app_id": "<private>",
      "mode": "point"
    }
  ]
}
```

**Comment by choran** [comment]
Hi @catacraciun 
Sorry for the delay here, we have been following up on some older issues and I just wanted to provide an update.
The issue here relates to the fact that we are returning information relating to the Intercom slack integration in the API subscriptions response. So it will occur when you setup a webhook in that integration. I am not 100% sure this is needed since these webhooks are separate the the Intercom webhooks you can subscribe to directly. 
For example, do you use the information returned in the slack notification here? 
Thanks
Cathal

**Comment by mmartinic** [comment]
We're no longer returning Slack webhooks in the response. Parse should work fine now.
