### ISSUE TITLE
Missing dependency causes classloader ClassNotFoundException: com.google.common.collect.Maps

### ISSUE THREAD

**Issue by romanr** [intercom/intercom-java#135]
## Version info
  - intercom-java version: 2.2.3
  - Java version: 1.8

## Steps to reproduce
 1. Play framework 1.4.3
 2. add intercom to Play's dependencies.yml:

```yaml
require:
    - play 1.4.3
    - io.intercom -> intercom-java 2.2.3
repositories:
    - jcenter:
       type:       http
       artifact: "http://jcenter.bintray.com/io/intercom/[module]/[revision]/[module]-[revision].jar"
       contains:
            - io.intercom -> *
```

 3. Add following test case to Java class:

```java
import io.intercom.api.Contact;
public class ... {
  public static void doContact(){
    Contact contact= new Contact();
  }
}
```
## Causes exception:
```
java.lang.NoClassDefFoundError: com/google/common/collect/Maps
	at io.intercom.api.Contact.<clinit>(Contact.java:21)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.commons.javaflow.bytecode.transformation.asm.ContinuationMethodAnalyzer$1.getClass(ContinuationMethodAnalyzer.java:114)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(Unknown Source)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(Unknown Source)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(Unknown Source)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(Unknown Source)
	at org.objectweb.asm.tree.analysis.Frame.execute(Unknown Source)
	at org.apache.commons.javaflow.bytecode.transformation.asm.MonitoringFrame.execute(MonitoringFrame.java:72)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Unknown Source)
	at org.apache.commons.javaflow.bytecode.transformation.asm.ContinuationMethodAnalyzer$2.analyze(ContinuationMethodAnalyzer.java:131)
	at org.apache.commons.javaflow.bytecode.transformation.asm.ContinuationMethodAnalyzer.visitEnd(ContinuationMethodAnalyzer.java:142)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.apache.commons.javaflow.bytecode.transformation.asm.AsmClassTransformer.transform(AsmClassTransformer.java:74)
	at org.apache.commons.javaflow.bytecode.transformation.asm.AsmClassTransformer.transform(AsmClassTransformer.java:41)
	at play.classloading.enhancers.ContinuationEnhancer.enhanceThisClass(ContinuationEnhancer.java:72)
	at play.CorePlugin.enhance(CorePlugin.java:306)
	at play.plugins.PluginCollection.enhance(PluginCollection.java:651)
	at play.classloading.ApplicationClasses$ApplicationClass.enhance(ApplicationClasses.java:242)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:165)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:425)
	at play.classloading.ApplicationClassloader.getAssignableClasses(ApplicationClassloader.java:466)
	at play.templates.GroovyTemplateCompiler.compile(GroovyTemplateCompiler.java:33)
	at play.templates.TemplateCompiler.compile(TemplateCompiler.java:28)
	at play.templates.TemplateLoader.load(TemplateLoader.java:81)
	at play.mvc.Router.parse(Router.java:171)
	at play.mvc.Router.load(Router.java:53)
	at play.mvc.Router.detectChanges(Router.java:232)
	at play.server.PlayHandler$NettyInvocation.init(PlayHandler.java:249)
	at play.Invoker$Invocation.run(Invoker.java:285)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:303)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
```

Probably it's caused by Ivy not resolving dependencies as expected by other dependency managers? So we need to specify deps manually.
In this case the documentation should reflect what packages this library depends on.

**Comment by romanr** [comment]
If we add Bintray repo like this, it still does not resolve package dependencies:

```yaml
repositories:
    - jcenter:
       type:       http
       artifact: "http://dl.bintray.com/"
       contains:
            - io.intercom -> *
```
Downloads only intercom.

**Comment by choran** [comment]
Hi @romanr,
Sorry for the delay here, just reviewing some older issues here and see this was never responded to.  I am not very familiar with Play but my basic knowledge of it is that it use sbt for build and deployment. sbt was one of the build tools we specify on the README that you can use. So I would have thought it would work with Play given that it works with sbt. So I am not sure why there would be a difference there. Have you come across anything else in the meantime that might explain this issue? I am not sure what change we would state in the doc given that we do support sbt. From that I would have assumed we would have used anything which used that as a build tool.

**Comment by choran** [comment]
Hi @romanr 
I am just wondering if you had any update here?
I will close this for now unless you think there is a reason to keep this open?
I was not sure if we needed to add any other clarification to the docs.
But like I said, if you feel there is still a problem here please feel free to reopen
Thanks
Cathal
