### ISSUE TITLE
NullPointerException when loading users who don't have Avatar Image

### ISSUE THREAD

**Issue by tagspace** [intercom/intercom-java#180]
## Version info
  - intercom-java version: 2.3.1
  - Java version: 8

## Expected behavior

Can load a user (even if they don't have an avatar image) using API.

## Actual behavior

Throws NullPointerException

## Steps to reproduce

Intercom.setToken("...");
Map<String, String> params = new HashMap<>();
params.put("email", "some_user_who_doesnt_have_avatar_image@domain.com");
User user = User.find(params);

## Logs

Exception in thread "main" io.intercom.api.IntercomException: Local exception calling [https://api.intercom.io//users?email=some_user_who_doesnt_have_avatar_image@domain.com]. Check connectivity and settings. [N/A (through reference chain: io.intercom.api.User["avatar"]->io.intercom.api.Avatar["image_url"])]
	at io.intercom.api.HttpClient.throwLocalException(HttpClient.java:124)
	at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:112)
	at io.intercom.api.HttpClient.get(HttpClient.java:86)
	at io.intercom.api.HttpClient.get(HttpClient.java:82)
	at io.intercom.api.DataResource.find(DataResource.java:20)
	at io.intercom.api.User.find(User.java:45)
	... 1 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: N/A (through reference chain: io.intercom.api.User["avatar"]->io.intercom.api.Avatar["image_url"])
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:564)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:548)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2764)
	at io.intercom.api.HttpClient.readEntity(HttpClient.java:190)
	at io.intercom.api.HttpClient.handleSuccess(HttpClient.java:176)
	at io.intercom.api.HttpClient.runRequest(HttpClient.java:153)
	at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:110)
	... 5 more
Caused by: java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at io.intercom.api.Avatar.setImageURL(Avatar.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:97)
	... 17 more

**Comment by thewheat** [comment]
Thanks @tagspace for detailing that bug. I've created PR to fix this https://github.com/intercom/intercom-java/pull/181 👍  Will try get it merge as soon as possible

**Comment by thewheat** [comment]
This has been merged so updating to the latest code base should it
