### ISSUE TITLE
Cannot tag user using this library

### ISSUE THREAD

**Issue by asultan** [intercom/intercom-java#197]
**ERROR:**
I am trying to tag one new user and I get this error:

2018-05-25 14:34:32.304 [pool-8-thread-1] INFO o.a.k.c.c.i.AbstractCoordinator - Discovered coordinator 10.3.218.11:9092 (id: 2147483646 rack: null) for group ServiceCache_device-config_e0d24755-15e8-4bea-a780-3b4febc7c37a.
2018-05-25 14:34:32.305 [pool-42-thread-1] INFO o.a.k.c.c.i.AbstractCoordinator - Discovered coordinator 10.3.218.11:9092 (id: 2147483646 rack: null) for group ServiceCache_users_e67c5537-04cc-4d2e-831f-e3b76a26db24.
2018-05-25 14:34:32.305 [http-nio-8543-exec-5] ERROR com.prosoft.tracker.TrackingUtil - Unknown exception when tagging user 7a83fd12-458c-4ceb-b0f6-f31c2b4114b4
io.intercom.api.IntercomException: Multiple existing users match this email address admin1@psft.com - must be more specific using user_id
at io.intercom.api.HttpClient.throwException(HttpClient.java:207)
at io.intercom.api.HttpClient.handleError(HttpClient.java:162)
at io.intercom.api.HttpClient.runRequest(HttpClient.java:148)
at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:103)
at io.intercom.api.HttpClient.post(HttpClient.java:93)
at io.intercom.api.DataResource.create(DataResource.java:22)
at io.intercom.api.Tag.tag(Tag.java:35)
at io.intercom.api.Tag.tag(Tag.java:26)
at com.prosoft.tracker.TrackingUtil.tagUser(TrackingUtil.java:120)
at com.prosoft.tracker.TrackingUtil.createUser(TrackingUtil.java:80)
at com.nirmata.users.handlers.IntercomTrackingUpdater.performIntercomUserCreation(IntercomTrackingUpdater.java:126)
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
at com.nirmata.users.handlers.IntercomTrackingUpdater.createUser(IntercomTrackingUpdater.java:32)
at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.nirmata.notify.impl.PostCommitHandler.notify(PostCommitHandler.java:23)
at com.nirmata.notify.impl.DefaultNotificationHandler.notifyPostCommit(DefaultNotificationHandler.java:96)
at com.nirmata.model.impl.DefaultModelTransaction.commit(DefaultModelTransaction.java:219)
at com.nirmata.json.ChangeReader.commit(ChangeReader.java:77)
at com.nirmata.servlet.handler.PostJsonHandler.applyChangeSet(PostJsonHandler.java:225)
at com.nirmata.servlet.handler.PostJsonHandler.handleTxnRequest(PostJsonHandler.java:212)
at com.nirmata.servlet.handler.PostJsonHandler.handleRequest(PostJsonHandler.java:49)
at com.nirmata.servlet.AbstractModelServlet.handleRequest(AbstractModelServlet.java:213)
at com.nirmata.servlet.AbstractModelServlet.service(AbstractModelServlet.java:158)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)
2018-05-25 14:34:32.307 [RMI TCP Connection(2)-127.0.0.1-EventThread] INFO o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED

**CONTEXT:**
The context is: we allow multiple organizations in our app, and if an user belongs to multiple organizations, they will have the same email but have 2 different users in Intercom.

The 2 users will have the same email, but different (and unique) user_id.

Your error says it cannot find an unique user with that user_id, but it is obvious that you fetch the user by email, which is wrong.

**Comment by thewheat** [comment]
Hi @asultan I've tested a couple of things on my end and you will need to specify the user_id in order for the tagging to work correctly

**This currently doesn't work if you have multiple records matching the email**
```
        User user = new User().setEmail("tim.lim@intercom.io");
        Tag tag = new Tag().setName("test-tag");
        tag = Tag.create(tag);
        Tag.tag(tag, user);
```

**This will**
```
        User user = new User().setUserId("13");
        Tag tag = new Tag().setName("test-tag");
        tag = Tag.create(tag);
        Tag.tag(tag, user);
```


* * * 


Making an API request with just an email fails in a similar fashion
![image](https://user-images.githubusercontent.com/892961/40600979-e40c3aa8-6285-11e8-88ca-aa1aaa57afb2.png)


So there isn't anything wrong with the library as it correctly reflects the output of the API. Are you able to change your code to use the user_id instead?

**Comment by asultan** [comment]
Please read the description guys. The users that I tag have unique user_id(s). I do not use the email as user id.

**Comment by asultan** [comment]
Please reopen the issue, as I do not see a way of doing it myself.

**Comment by thewheat** [comment]
@asultan could you share with me the code that you're using to run into that error? I'll be happy to reopen the issue if I can identify that there is an issue with the SDK 👍 

From what I gathered in my investigation 
- it seems to me that you were trying to tag a user based on the email address alone (using code that could look like that shown below)

```
        User user = new User().setEmail("tim.lim@intercom.io");
        Tag tag = new Tag().setName("test-tag");
        tag = Tag.create(tag);
        Tag.tag(tag, user);
```
- and if this is the case and you have **multiple records** that match the email address, then the Intercom API cannot correctly identify which record you are trying to update and thus why it is throwing the error `Multiple existing users match this email address admin1@psft.com`
- the second part of the message is detailing how you can resolve it by specifying a [user_id](https://docs.intercom.com/help-and-faqs/your-users-data-in-intercom/what-is-user-id): `must be more specific using user_id`. If you specify a user_id value we can uniquely identify which record you want to tag

If there was anything that is incorrect there, do let me know.

Having multiple records in Intercom with the same email address but different user_ids is perfectly acceptable. But calls to tag a user requires sending over an identifier that finds a single record that matches the identifier specified in order for the update to work correctly

**Comment by asultan** [comment]
public static void createUser(String userId, String email, String name, String role, String phone, String stage,
                                  String companyId, String companyName, List<String> tags, boolean isTeamInitiator) {
        if (!_enableTracking) {
            _logger.debug("Intercom tracking is disabled");
            return;
        }

        _logger.info("User {} has been created. Creating user in Intercom: id={}, email={}, name={}, role={}, phone={}, " +
                        "stage={}, companyID={}, companyName={}, tags={}, isTeamInitiator={}",
                userId, email, name, role, phone, stage, companyId, companyName, tags, isTeamInitiator);

        try {
            User user = new User()
                    .setUserId(userId)
                    .setEmail(email)
                    .setName(name)
                    .addCustomAttribute(CustomAttribute.newStringAttribute("role", role))
                    .addCustomAttribute(CustomAttribute.newStringAttribute("stage", stage.toLowerCase()))
                    .addCustomAttribute(CustomAttribute.newStringAttribute("phone", (phone != null && !phone.isEmpty()) ? phone : "unknown"))
                    .addCustomAttribute(CustomAttribute.newStringAttribute("tenant_id", companyId));

            Company companyObj;
            if (isTeamInitiator) {
                companyObj = new Company()
                        .setCompanyID(companyId)
                        .setName((companyName != null && !companyName.isEmpty()) ? companyName : "unknown");
            } else {
                Map<String, String> params = new HashMap<>();
                params.put("company_id", companyId);
                companyObj = Company.find(params);
            }
            if (companyObj != null) {
                user.addCompany(companyObj);
            }

            User created = User.create(user);
            if (created != null) {
                _logger.debug("User {} has been added successfully to Intercom", userId);
                if (tags != null && tags.size() > 0) {
                    for (String tag : tags) {
                        tagUser(user, tag);
                    }
                }
            }
        } catch (AuthorizationException e) {
            _logger.error("Authorization exception when creating user {}", userId, e);
        } catch (ClientException e) {
            _logger.error("Client exception when creating user {}", userId, e);
        } catch (ServerException e) {
            _logger.error("Server exception when creating user {}", userId, e);
        } catch (InvalidException e) {
            _logger.error("Invalid exception when creating user {}", userId, e);
        } catch (RateLimitException e) {
            _logger.error("Rate Limit exception when creating user {}", userId, e);
        } catch (Throwable t) {
            _logger.error("Unknown exception when creating user {}", userId, t);
        }
    }

**Comment by asultan** [comment]
Please note that the user id is a unique id (UUID)

**Comment by asultan** [comment]
Can you please reopen the issue or should I make a clone of this?

**Comment by thewheat** [comment]
@asultan apologies as I've been out of the office so didn't get a chance to follow up yet.  Thanks for the details and I have been able to replicate the problem so I'm going to reopen and created a PR https://github.com/intercom/intercom-java/pull/199 👍 

Looks to be due to https://github.com/intercom/intercom-java/blob/f50c869194eac5d4fc047e08634b99c14334e88b/intercom-java/src/main/java/io/intercom/api/Tag.java#L83-L94 where we are prioritzsing email over user_id

Sample code to replicate would be
```
        User user = new User().setUserId("13").setEmail("tim.lim@intercom.io"); // where email is an email that multiple records use
        Tag tag = new Tag().setName("test-tag");
        tag = Tag.create(tag);
        Tag.tag(tag, user);
```

* * *

If you need to fix this now before waiting for the code to merge and a new release to be updated, just modify your code to detect if the current user object has a user_id and if so, create a new user object before tagging with **only the user_id and no email**. So it would look something like this

```
        if (!Strings.isNullOrEmpty(user.getUserId())) {
            User newUser = new User().setUserId(user.getUserId());
            Tag.tag(tag, newUser);
        }
        else{
            Tag.tag(tag, user);
        }
```

**Comment by asultan** [comment]
Is this fixed included in a lib which was uploaded to a public lib repository? Or should I build it by myself?

**Comment by asultan** [comment]
Guys - where is this fix available? I have upgraded to io.intercom:intercom-java:2.5.1 and the problem persists.

**Comment by thewheat** [comment]
@asultan So sorry for missing your previous reply. I ran the sample code that previously the triggered the error and it works in `2.5.1` 😕  

![image](https://user-images.githubusercontent.com/892961/45143576-41daef00-b1ee-11e8-9180-fa1c7a22b523.png)

You may be running into something else then. Could you let us know some details of the request you're making e.g. the email / user_id and your app_id?  We can look it up in the logs to see if there is anything else that could be problematic.

If you rather it not be public, message us in the Messenger at https://intercom.com or email team@intercom.com and our team can look into this for you 👍

**Comment by asultan** [comment]
Hello Tim,

Indeed, the fix is available. It looks that I was having troubles building
a library of mine using the new java-intercom lib with the newest version.
It is all good now.

Thanks,
Ducu

**Comment by thewheat** [comment]
Fantastic 🙌  Glad we were able to sort it out 😄
