### ISSUE TITLE
Exception when using Conversation.list

### ISSUE THREAD

**Issue by luiszimmermann** [intercom/intercom-java#253]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-java version: 2.8.0
  - Java version: 8u181

## Expected behavior
Get Conversations list

## Actual behavior
Exception```io.intercom.api.NotFoundException: Resource Not Found```

## Steps to reproduce
 1. `ConversationCollection openForAdmin = Conversation.list([type: "admin", admin_id: adminId, open: "true", state: "open"])`

## Logs
```
io.intercom.api.NotFoundException: Resource Not Found
        at io.intercom.api.HttpClient.throwException(HttpClient.java:207)
        at io.intercom.api.HttpClient.handleError(HttpClient.java:169)
        at io.intercom.api.HttpClient.runRequest(HttpClient.java:155)
        at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:110)
        at io.intercom.api.HttpClient.get(HttpClient.java:86)
        at io.intercom.api.HttpClient.get(HttpClient.java:82)
        at io.intercom.api.DataResource.list(DataResource.java:66)
        at io.intercom.api.Conversation.list(Conversation.java:66)
        at io.intercom.api.Conversation$list.call(Unknown Source)
```

**Comment by luiszimmermann** [comment]
The problem is here https://github.com/intercom/intercom-java/blob/746c37745531bd4a8eda0be6085402ead739f64c/intercom-java/src/main/java/io/intercom/api/DataResource.java#L74

the `.path("scroll")` adds to the Uri and the return from intercom `https://api.intercom.io/conversations/scroll?type=admin&admin_id=adminId&open=true` is `Resource Not Found`. Without the `/scroll` the API returns the right response, like yesterday...
