### ISSUE TITLE
joda_zoneinfomap  FATAL EXCEPTION

### ISSUE THREAD

**Issue by carias-rh** [intercom/intercom-java#301]
## Version info
  - Android 11
  - HTC one M8
  - intercom-java version: 4.0.0(200678)
  - Java version:

## Expected behavior
The application opens

## Actual behavior
The app crashes

## Steps to reproduce
 1. Install latest version 4.0.0(200678)
 2. Open the app
 3. The app crashes

I tried an older version 3.9.3(200546) and it's working fine.

## Logs
```
01-28 12:35:49.567  1876  2633 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.intercom.android/.screens.SplashScreenActivity bnds=[234,1558][438,1789]} from uid 1000
01-28 12:35:49.572   291   291 I android.hardware.power-service-qti: Power setMode: 5 to: 1
01-28 12:35:49.573   291   291 E QTI PowerHAL: Failed to perform launch boost
01-28 12:35:49.585  3289  3289 D PredictionService: onAppTargetEvent
01-28 12:35:49.590  1876  1923 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10269; state: DISABLED
01-28 12:35:49.591  1876  1930 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10269; state: ENABLED
01-28 12:35:49.615  1665  1665 D Zygote  : Forked child process 12383
01-28 12:35:49.622  1876  1930 I ActivityManager: Start proc 12383:io.intercom.android/u0a269 for pre-top-activity {io.intercom.android/io.intercom.android.screens.SplashScreenActivity}
01-28 12:35:45.990     0     0 D SELinux : initialized (dev tmpfs, type tmpfs), uses transition SIDs
01-28 12:35:49.668   390   398 I adbd    : jdwp connection from 12383
01-28 12:35:49.671 12383 12383 W ntercom.androi: Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
01-28 12:35:49.682  1876  1902 W OomAdjuster: Fallback pre-set sched group to default: not expected top priority
01-28 12:35:49.690  1876  1902 D GamingModeHelper: onTopAppChanged: io.intercom.android
01-28 12:35:49.696  1876  1924 W WindowManager: Unable to find process with pid=2529 uid=1000
01-28 12:35:49.749 12383 12383 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-28 12:35:49.749 12383 12383 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-28 12:35:49.808 12383 12383 I FirebaseInitProvider: FirebaseApp initialization successful
01-28 12:35:49.816 12383 12383 D Sentry  : Auto-init: true
01-28 12:35:49.816 12383 12383 I Sentry  : Retrieving auto-init from AndroidManifest.xml
01-28 12:35:49.819 12383 12409 I TetheringManager: registerTetheringEventCallback:io.intercom.android
01-28 12:35:49.853  1876  3024 D CompatibilityChangeReporter: Compat change id reported: 136274596; UID 10269; state: ENABLED
01-28 12:35:49.864 12383 12417 I Sentry  : sentry-debug-meta.properties file was not found.
01-28 12:35:49.863 12417 12417 W pool-12-thread-: type=1400 audit(0.0:34): avc: denied { read } for name="version" dev="proc" ino=4026543123 scontext=u:r:untrusted_app:s0:c13,c257,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=io.intercom.android
01-28 12:35:45.991     0     0 I chatty  : uid=0(root) logd identical 2 lines
01-28 12:35:45.993     0     0 D SELinux : initialized (dev tmpfs, type tmpfs), uses transition SIDs
01-28 12:35:46.265     0     0 I [CAM]msm_isp_sof_notify: (0)PIX0 frame id: 15900
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: Failed to retrieve identifier: type=class net.danlew.android.joda.R$raw name=joda_zoneinfomap
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: java.lang.NoSuchFieldException: joda_zoneinfomap
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at java.lang.Class.getField(Class.java:1604)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at net.danlew.android.joda.ResUtils.getIdentifier(ResUtils.java:105)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at net.danlew.android.joda.ResourceZoneInfoProvider.openResource(ResourceZoneInfoProvider.java:113)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at net.danlew.android.joda.ResourceZoneInfoProvider.<init>(ResourceZoneInfoProvider.java:38)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at net.danlew.android.joda.JodaTimeAndroid.init(JodaTimeAndroid.java:39)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at io.intercom.android.application.IntercomApplication.onCreate(IntercomApplication.java:62)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1239)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6721)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at android.app.ActivityThread.access$1300(ActivityThread.java:238)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at android.os.Looper.loop(Looper.java:223)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at android.app.ActivityThread.main(ActivityThread.java:7661)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at java.lang.reflect.Method.invoke(Native Method)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
01-28 12:35:49.918 12383 12383 E JodaTimeAndroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-28 12:35:49.919 12383 12383 D AndroidRuntime: Shutting down VM
01-28 12:35:49.920 12383 12383 E AndroidRuntime: FATAL EXCEPTION: main
01-28 12:35:49.920 12383 12383 E AndroidRuntime: Process: io.intercom.android, PID: 12383
01-28 12:35:49.920 12383 12383 E AndroidRuntime: java.lang.RuntimeException: Unable to create application io.intercom.android.application.IntercomApplication: java.lang.RuntimeException: Could not read ZoneInfoMap. You are probably using Proguard wrong.
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6726)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:238)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7661)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: Caused by: java.lang.RuntimeException: Could not read ZoneInfoMap. You are probably using Proguard wrong.
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at net.danlew.android.joda.JodaTimeAndroid.init(JodaTimeAndroid.java:42)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at io.intercom.android.application.IntercomApplication.onCreate(IntercomApplication.java:62)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1239)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6721)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	... 8 more
01-28 12:35:49.920 12383 12383 E AndroidRuntime: Caused by: java.io.IOException: Resource not found: "ZoneInfoMap" (resName: "joda_zoneinfomap")
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at net.danlew.android.joda.ResourceZoneInfoProvider.openResource(ResourceZoneInfoProvider.java:116)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at net.danlew.android.joda.ResourceZoneInfoProvider.<init>(ResourceZoneInfoProvider.java:38)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	at net.danlew.android.joda.JodaTimeAndroid.init(JodaTimeAndroid.java:39)
01-28 12:35:49.920 12383 12383 E AndroidRuntime: 	... 11 more
01-28 12:35:50.169  1876  5393 W WindowManager: Unable to find process with pid=2529 uid=1000
```

**Comment by carias-rh** [comment]
The app was updated to 4.0.1 (200712) which solved this issue.
