### ISSUE TITLE
Conflicting getter definitions for property \"update_last_request_at\": 

### ISSUE THREAD

**Issue by gemmell** [intercom/intercom-java#48]
Worked locally after updating to 1.0.8, deployed to prod, breaks with:
{"error":"Local exception calling [https://api.intercom.io//users]. Check connectivity and settings. [Conflicting getter definitions for property \"update_last_request_at\": io.intercom.api.User$UserUpdate#getUpdateLastRequestAt(0 params) vs io.intercom.api.User$UserUpdate#isUpdateLastRequestAt(0 params)]"}

Feels to me like a dependency issue where it was satisfied locally but had to go get it in prod...

**Comment by gemmell** [comment]
Looks like it
http://stackoverflow.com/questions/22495617/conflicting-getter-definitions-for-property-in-jackson-2-2-3

**Comment by gemmell** [comment]
Stack:
```
io.intercom.api.IntercomException: Local exception calling [https://api.intercom.io//users]. Check connectivity and settings. [Conflicting getter definitions for property "update_last_request_at": io.intercom.api.User$UserUpdate#isUpdateLastRequestAt(0 params) vs io.intercom.api.User$UserUpdate#getUpdateLastRequestAt(0 params)]
        at io.intercom.api.HttpClient.throwLocalException(HttpClient.java:115)
        at io.intercom.api.HttpClient.post(HttpClient.java:95)
        at io.intercom.api.DataResource.create(DataResource.java:20)
        at io.intercom.api.User.create(User.java:63)
        at com.tkbt.websiteservices.IntercomServices.CreateOrganisationAndUser(IntercomServices.java:42)
        at com.tkbt.websiteservices.Server$7.lambda$handle$14(Server.java:294)
        at com.tkbt.websiteservices.Server$7$$Lambda$16/1841823317.get(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Conflicting getter definitions for property "update_last_request_at": io.intercom.api.User$UserUpdate#isUpdateLastRequestAt(0 params) vs io.intercom.api.User$UserUpdate#getUpdateLastRequestAt(0 params)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:838)
        at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:387)
        at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:478)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:97)
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2718)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2177)
        at io.intercom.api.HttpClient.prepareRequestEntity(HttpClient.java:126)
        at io.intercom.api.HttpClient.post(HttpClient.java:92)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: Conflicting getter definitions for property "update_last_request_at": io.intercom.api.User$UserUpdate#isUpdateLastRequestAt(0 params) vs io.intercom.api.User$UserUpdate#getUpdateLastRequestAt(0 params)
        at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getGetter(POJOPropertyBuilder.java:190)
        at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getAccessor(POJOPropertyBuilder.java:283)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSerializerFactory.java:678)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:557)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:373)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:268)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:213)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:152)
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:873)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:833)
        ... 14 more

```

**Comment by dehora** [comment]
@gemmell the jackson version for the client is 2.4.2 which is also working for me. I'm going to try removing the added secondary methods instead of jsonignore

**Comment by gemmell** [comment]
$ jar tf WebsiteServices-0.0.1-fat.jar  | grep jackson
lib/jackson-databind-2.2.2.jar
lib/jackson-core-2.2.2.jar
lib/jackson-annotations-2.2.2.jar
mods/com.tkbt~WebsiteServices~0.0.1/lib/jackson-core-2.4.3.jar
mods/com.tkbt~WebsiteServices~0.0.1/lib/jackson-databind-2.4.3.jar
mods/com.tkbt~WebsiteServices~0.0.1/lib/jackson-annotations-2.4.0.jar

**Comment by dehora** [comment]
@gemmell there's a 1.0.9 version that backs out the alternate getters; lmk how it works with mixed libs for  you.

**Comment by gemmell** [comment]
Seems to do the trick.

**Comment by dehora** [comment]
@gemmell  good to hear, thanks for reporting it
