### ISSUE TITLE
Error when adding metadata to an Event.

### ISSUE THREAD

**Issue by TFinnT** [intercom/intercom-java#52]
If I create an event with metadata it fails when doing the Event.create(event) step.

The stacktrace of the exception is:

Caused by: java.lang.NoSuchFieldError: WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS
	at io.intercom.api.MapperSupport.configure(MapperSupport.java:20)
	at io.intercom.api.MapperSupport.objectMapper(MapperSupport.java:13)
	at io.intercom.api.HttpClient.clientAgentDetails(HttpClient.java:48)
	at io.intercom.api.HttpClient.<clinit>(HttpClient.java:28)
	at io.intercom.api.DataResource.create(DataResource.java:19)
	at io.intercom.api.Event.create(Event.java:25)

**Comment by dehora** [comment]
@TFinnT `WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS ` was added in Jackson 2.2; I suspect the runtime has a previous version of Jackson loaded

**Comment by TFinnT** [comment]
Hello.
Yes, I've got a 2.4.2 version in runtime.

I couldn't find the dependency grid for your library, a recommended version of jackson and guava, so I let maven decide which one is appropiate.

Thanks in advance

**Comment by dehora** [comment]
> I've got a 2.4.2 version in runtime.

That's odd because jackson annotations 2.4.2 will have this field in `SerializationFeature` - any chance you have more than one jar on the classpath?

**Comment by TFinnT** [comment]
Ok, I finally could solved it.

I just put it on the pom.xml explicitly and it do the trick.
 
Thanks again for the help and the good job with the api.

**Comment by dehora** [comment]
Good to hear! And thanks for letting us know it's working ok.
