### ISSUE TITLE
Cannot update a Job

### ISSUE THREAD

**Issue by LeoIannacone** [intercom/intercom-java#85]
Hi,
I would like to set a closing_at, but something is wrong with:
```scala
val job = intercomApi.User.submit(jobItems.asJava)
job.setClosingAt(Instant.now.toEpochMilli / 1000 + 2)
intercomApi.Job.update(job)
```

This is the error I get on Job.update:
```
2015-11-24 15:39:46.867 [fyrestone-actors-akka.actor.default-dispatcher-2] DEBUG intercom-java - error json follows --
{"type":"error.list","errors":null}
-- 
2015-11-24 15:39:46.885 [fyrestone-actors-akka.actor.default-dispatcher-2] ERROR c.c.f.events.ServerEventsHandler - 
io.intercom.api.NotFoundException: Could not read error message from server
	at io.intercom.api.HttpClient.throwException(HttpClient.java:201) ~[io.intercom.intercom-java-1.3.0.jar:na]
	at io.intercom.api.HttpClient.handleError(HttpClient.java:164) ~[io.intercom.intercom-java-1.3.0.jar:na]
	at io.intercom.api.HttpClient.runRequest(HttpClient.java:150) ~[io.intercom.intercom-java-1.3.0.jar:na]
	at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:105) ~[io.intercom.intercom-java-1.3.0.jar:na]
	at io.intercom.api.HttpClient.post(HttpClient.java:95) ~[io.intercom.intercom-java-1.3.0.jar:na]
	at io.intercom.api.DataResource.post(DataResource.java:37) ~[io.intercom.intercom-java-1.3.0.jar:na]
	at io.intercom.api.Job.update(Job.java:36) ~[io.intercom.intercom-java-1.3.0.jar:na]
```

**Comment by RuairiK** [comment]
Hi,

I'm afraid we don't support setting a custom closing_at value. The field is settable as it was being used for testing during development, we'll likely remove the ability to set it in the near future. Sorry for the confusion.

Ruairí.

**Comment by LeoIannacone** [comment]
Problem is a Job won't update intercom for the next 15 minutes, we would like to reduce this delay. 

Is it possible?

**Comment by RuairiK** [comment]
The job might actually take longer (or shorter) than that. We don't guarantee a maximum length of time that it will take a job to run. The 15 mins is the time in which you may add more items to be processed by the job. So unfortunately, it's not possible to reduce the delay.
