### ISSUE TITLE
Note.create() complains of unpermitted parameters in the User object

### ISSUE THREAD

**Issue by ccsbob** [intercom/intercom-java#86]
Creating a Note linked to a User like this:
```
				intercomId = "someintercomidhere";
				body = "A SHORT TEST BODY";
				Note note = new Note()
						//.setUser(User.find(intercomId))           // try sending a fully-persisted User
						.setUser(new User().setId(intercomId))  // try sending a bare User with just the ID set
						//.setUser(new User().setEmail(email))    // try sending a bare User with just the email set
						.setBody(body);
				System.err.println("NEW NOTE: "+note);
				// TODO: THIS FAILS! SERVER JUST WANTS A BARE 'user':{'id':'foobar'} ENTRY IN REQUEST, APPARENTLY
				Note.create(note);
```
constructs a request with a "type" key in the User object, which triggers an error:
```
INFO - api server request --
{"type":"note","body":"A SHORT TEST BODY","user":{"type":"user","id":"someintercomidhere"}}
-- 
DEBUG - error json follows --
{"type":"error.list","errors":[{"type":"error","code":"parameter_invalid","message":"found unpermitted parameters: type"}]}
-- 
io.intercom.api.ClientException: found unpermitted parameters: type
	at io.intercom.api.HttpClient.throwException(HttpClient.java:205)
	at io.intercom.api.HttpClient.handleError(HttpClient.java:164)
	at io.intercom.api.HttpClient.runRequest(HttpClient.java:150)
	at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:105)
	at io.intercom.api.HttpClient.post(HttpClient.java:95)
	at io.intercom.api.DataResource.create(DataResource.java:22)
	at io.intercom.api.Note.create(Note.java:23)
[...]
```

Submitting a Note with a full User object (result of `User.find(id)`, for example) yields server complaints of many more "unpermitted parameters" in the User object.

**Comment by bobjflong** [comment]
This should be fixed now @ccsbob - could you confirm on your end?
